# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://shixinzhang.top
date_format: "ordinal"
title: shixinzhang
subtitle: "逆水行舟"
description: "张拭心的个人博客"
keywords: shixinzhang, 张拭心, 拭心, shixin, csdn
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 张拭心 shixinzhang
organization: xxx.com
organization_url: http://www.xxx.com
github_username: shixinzhang
location: Shanghai, China
email: shixinzhang2016@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: shixinzhang/shixinzhang.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
##comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
#    username: mzlogin
# https://imsun.net/posts/gitment-introduction/
# 申请地址：https://github.com/settings/applications/new
gitment:
    owner: shixinzhang
    repo: shixinzhang.github.io
    oauth:
        client_id: 34909673d9a1d362d29c
        client_secret: d0a13eef81ac4684160f91923c49af8246dd5b86
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: shixinzhang
    repo: shixinzhang.github.io
    clientID: 34909673d9a1d362d29c
    clientSecret: d0a13eef81ac4684160f91923c49af8246dd5b86
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
